apiVersion: v1
kind: Pod
metadata:
  name: nginx-node-affinity-preferred
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoreDuringExecution:
        - weight: 1
          preferences:
            - matchExpressions:
              - key: mining
                operator: In
                values:
                - "yes"
        - weight: 1
          preferences:
              - key: gpu
                operator: In
                values:
                - "yes"
  containers:
  - name: nginx
    image: nginx
