apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-spread-constraints
  labels:
    spread_constraints: "True"
spec:
  replicas: 1
  selector:
    matchLabels:
      spread_constraints: "True"
  template:
    metadata:
      labels:
        spread_constraints: "True"
    spec:
      topologySpreadConstraints:
      - maxSkew: 1 
        topologyKey: topology.kubernetes.io/zone 
        whenUnsatisfiable: DoNotSchedule 
        labelSelector: 
          matchLabels:
            spread_constraints: "True"
      containers:
      - name: nginx
        image: nginx
      securityContext:
        privileged: true
