apiVersion: autoscaling.openshift.io/v1beta1
kind: MachineAutoscaler
metadata:
  name: cluster-1b74-r45lt-worker-eu-west-1a-spot
spec:
  maxReplicas: 10
  minReplicas: 0
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: cluster-1b74-r45lt-worker-eu-west-1a-spot

