apiVersion: machine.openshift.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: machinehealthcheck-spot
  namespace: openshift-machine-api
spec:
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cluster-1b74-r45lt
      machine.openshift.io/cluster-api-machine-role: worker
      machine.openshift.io/cluster-api-machine-type: worker
      machine.openshift.io/cluster-api-machineset: cluster-1b74-r45lt-worker-eu-west-1a-spot
  unhealthyConditions:
    - type: Ready
      status: Unknown
      timeout: 300s
    - type: Ready
      status: 'False'
      timeout: 300s
  maxUnhealthy: 10%
