apiVersion: v1
kind: Pod
metadata:
  name: nginx-node-selector-toleration
  labels:
    env: testing
spec:
  containers:
  - name: nginx
    image: nginx
  nodeSelector:
    gpu: "yes"
  tolerations:
  - key: gpu
    operator: Equal
    value: "yes"
    effect: "NoSchedule"

